backend:
  name: github
  repo: SamProtege/SiteMiniEntreprise
  branch: master
  auth_type: implicit
  app_id: "Ov23lib1f0o7ErdCqGzX"  # ton App ID GitHub OAuth (si tu l'as)

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "accueil"
    label: "Accueil"
    files:
      - label: "Page d'accueil"
        name: "index"
        file: "content/accueil.json"
        fields:
          - { label: "Titre principal", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
